Fix error code

diff --git a/.github/workflows/build.js.yml b/.github/workflows/build.js.yml
--- a/.github/workflows/build.js.yml
+++ b/.github/workflows/build.js.yml
@@ -46,7 +46,8 @@ jobs:
           if [ -f sitemap.xml ] && [ -f rss.xml ]; then
             echo "Everything is ok"
           else
-            raise error "Sitemap or RSS not found"
+            echo "Sitemap or RSS not found"
+            exit 1
           fi
 
   build:
